set(_AMENT_PACKAGE_NAME "vins_edited")
set(vins_edited_VERSION "0.0.0")
set(vins_edited_MAINTAINER "add-nuc-gpu <add-nuc-gpu@todo.todo>")
set(vins_edited_BUILD_DEPENDS "rosidl_default_generators" "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport")
set(vins_edited_BUILDTOOL_DEPENDS "ament_cmake")
set(vins_edited_BUILD_EXPORT_DEPENDS "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport")
set(vins_edited_BUILDTOOL_EXPORT_DEPENDS )
set(vins_edited_EXEC_DEPENDS "rosidl_default_runtime" "rclcpp" "rcpputils" "std_msgs" "geometry_msgs" "visualization_msgs" "nav_msgs" "tf2" "tf2_ros" "cv_bridge" "camera_models" "image_transport")
set(vins_edited_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(vins_edited_GROUP_DEPENDS )
set(vins_edited_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(vins_edited_DEPRECATED "")
set(vins_edited_EXPORT_TAGS)
list(APPEND vins_edited_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
